service: mkb-serverless-boilerplate

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, 'eu-west-1'}

  logRetentionInDays: ${self:custom.settings.logging.retention, 14}

  # Use direct deployments instead of CloudFormation change sets
  deploymentMethod: direct
  deploymentBucket:
    name: serverless-deployments.${param:environment}.mkb-brandstof.nl

  # use proper naming (service in front of stage) for API resources
  apiGateway:
    shouldStartNameWithService: true

  # environment variables for all functions
  environment:
    ENVIRONMENT: ${param:environment}
    LOG_LEVEL: ${self:custom.settings.logging.level, 'info'}
    STAGE: ${sls:stage}
    SERVICE: ${self:service}

  # tags to add to all resources in the stack (that support them)
  stackTags:
    Service: ${self:service}
    Stage: ${sls:stage}


params:
  dev:
    environment: dev
  test:
    environment: test
  uat:
    environment: uat
  prod:
    environment: prod

custom:
  settings: ${file(settings/${sls:stage}.yml)}
  # customDomain: ${self:custom.settings.customDomain} # if using serverless-domain-manager
  webpack:
    includeModules: true
  outputEnv:
    localVariables:
      default:
        AWS_REGION: ${aws:region}

package:
  individually: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-output-env
  # - serverless-domain-manager # if using an (external) API

functions:
  hello:
    handler: src/hello.handler
    description: Just a short description for this function
    memorySize: 256
    timeout: 6
    # iamRoleStatements:
    # - Effect: Allow
    #   Action: something
    #   Resource: some resource

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
